vim.keymap.set("n", "<leader>pv", vim.cmd.Ex, { desc = "Custom: go to file explorer" })
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", { desc = "Custom: down (multi-)line movement" })
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", { desc = "Custom: up (multi-)line movement" })
vim.keymap.set({"n", "v"}, "<leader>y", "\"+y", { desc = "Custom: yank selected text to the system clipboard" })
vim.keymap.set("n", "<leader>Y", "\"+Y", { desc = "Custom: yank current line to the sytem clipboard" })
vim.keymap.set("n", "<leader>s", ":%s/\\<<C-r><C-w>\\>/<C-r><C-w>/gI<Left><Left><Left>", { desc = "Custom: regex replace word under the cursor" })
vim.keymap.set({"n", "v"}, "<leader>d", "\"_d", { desc = "Custom: deletes text to black hole register" })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "Custom: scrolls down by half a page and centers the cursor vertically" })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "Custom: scrolls up by half a page and centers the cursor vertically" })
