#!/usr/bin/env python3

import argparse
from random import randint


def generate_game(nums_to_generate: int, min_num: int, max_num: int) -> list[int]:
    game = []
    while len(game) < nums_to_generate:
        n = randint(min_num, max_num)
        if n not in game:
            game.append(n)
    return game


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate one or more games with unique random numbers."
    )
    parser.add_argument(
        "-g", "--games",
        type=int,
        default=1,
        help="Number of games to generate (default: 1)"
    )
    parser.add_argument(
        "-n", "--nums",
        type=int,
        default=6,
        help="Numbers per game (default: 6)"
    )
    parser.add_argument(
        "--min",
        dest="min_num",
        type=int,
        default=1,
        help="Minimum number value (default: 1)"
    )
    parser.add_argument(
        "--max",
        dest="max_num",
        type=int,
        default=60,
        help="Maximum number value (default: 60)"
    )

    args = parser.parse_args()

    for _ in range(args.games):
        game = generate_game(args.nums, args.min_num, args.max_num)
        print(" ".join(str(n) for n in sorted(game)))


if __name__ == "__main__":
    main()

